In [1]:
import numpy as np
import pandas as pd

In [2]:
book1 = pd.read_csv('book1-100k.csv')

In [4]:
book1.head(1)

,Id,Name,RatingDist1,pagesNumber,RatingDist4,RatingDistTotal,PublishMonth,PublishDay,Publisher,CountsOfReview,PublishYear,Language,Authors,Rating,RatingDist2,RatingDist5,ISBN,RatingDist3
0,1,Harry Potter and the Half-Blood Prince (Harry ...,1:9896,652,4:556485,total:2298124,16,9,Scholastic Inc.,28062,2006,eng,J.K. Rowling,4.57,2:25317,5:1546466,NaN,3:159960

In [9]:
book1 = book1[['Id','Name','Publisher','CountsOfReview','Authors','Rating']]

In [10]:
book1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58292 entries, 0 to 58291
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Id              58292 non-null  int64
 1   Name            58292 non-null  object
 2   Publisher       57798 non-null  object
 3   CountsOfReview  58292 non-null  int64
 4   Authors         58292 non-null  object
 5   Rating          58292 non-null  float64
dtypes: float64(1), int64(2), object(3)
memory usage: 2.7+ MB

In [12]:
book1.head()

,Id,Name,Publisher,CountsOfReview,Authors,Rating
0,1,Harry Potter and the Half-Blood Prince (Harry ...,Scholastic Inc.,28062,J.K. Rowling,4.57
1,2,Harry Potter and the Order of the Phoenix (Har...,Scholastic Inc.,29770,J.K. Rowling,4.50
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,Scholastic Inc,75911,J.K. Rowling,4.47
3,4,Harry Potter and the Chamber of Secrets (Harry...,Scholastic,244,J.K. Rowling,4.42
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,Scholastic Inc.,37093,J.K. Rowling,4.57

In [14]:
book1.iloc[0].Authors

'J.K. Rowling'

In [15]:
book1.iloc[0].Name

'Harry Potter and the Half-Blood Prince (Harry Potter, #6)'